robot_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - First_joint
      - Third_joint
      - Fourth_joint
      - Fifth_joint
      - Sixth_joint
      - Gripper_Base_joint

    constraints:
      goal_time: 0.6

    state_publish_rate: 25

  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - Left_Finger_joint
      - Right_Finger_joint

      

