robot_arm:
  gazebo_ros_control:   
    pid_gains:
      First_joint:
        p: 1200.0
        i: 100.0 
        d: 150.0
        i_clamp_max: 500.0
        i_clamp_min: -500.0
      Third_joint:
        p: 20000.0
        i: 100.0 
        d: 500.0
        i_clamp_max: 500.0
        i_clamp_min: -500.0
      Fourth_joint:
        p: 4000.0
        i: 50.0 
        d: 100.0
        i_clamp_max: 100.0
        i_clamp_min: -100.0
      Fifth_joint:
        p: 200.0
        i: 0.0 
        d: 10.0
        i_clamp_max: 100.0
        i_clamp_min: -100.0
      Sixth_joint:
        p: 200.0
        i: 0.0
        d: 10.0
        i_clamp_max: 100.0
        i_clamp_min: -100.0
      Gripper_Base_joint:
        p: 600.0
        i: 30.0 
        d: 0.0
        i_clamp_max: 100.0
        i_clamp_min: -100.0
      Left_Finger_joint:
        p: 300.0
        i: 10.0 
        d: 10.0
        i_clamp_max: 100.0
        i_clamp_min: -100.0
      Right_Finger_joint:
        p: 300.0
        i: 10.0 
        d: 10.0
        i_clamp_max: 100.0
        i_clamp_min: -100.0